export const DASHBOARD_PAGE_COPY = {
  pageTitle: "工作台",
  frameHint: "基于真实业务接口汇总，数据为空时展示空状态。",
  searchPlaceholder: "搜索简历、岗位、面试记录...",
  sections: {
    above: {
      title: "Section01_AboveTheFold",
      cardsTitle: "首页指标",
      titlePrefix: "首页指标",
      disabledActionHint: "当前调试态暂不展示首页指标。",
      defaultTitle: "首页指标",
    },
    todo: {
      title: "Section02_TodoSection",
      cardTitle: "待办事项",
      totalHint: "基于真实数据生成",
      headerIconLabel: "待办事项",
      disabledActionHint: "当前调试态暂不展示待办事项。",
    },
    activity: {
      title: "Section03_ActivitySection",
      cardTitle: "最近活动",
      headerActionLabel: "查看全部",
      headerActionDisabledHint: "当前调试态暂不展示最近活动。",
      footer: "",
    },
    empty: {
      title: "资料不足态",
      sectionHeader: "资料与历史不足状态",
      description: "当前没有可汇总的业务记录。",
      footer: "",
      defaultDisabledHint: "当前调试态不展示业务记录。",
      disabledReason: "该状态下不展示业务记录。",
    },
  },
  labels: {
    pageTitle: "工作台",
    emergency: "紧急",
    important: "重要",
    normal: "普通",
    newTag: "新建",
    reviewTag: "待复盘",
    sentTag: "已投递",
    updatedTag: "已更新",
    todoBadgeStatusTodo: "TODO",
    todoBadgeStatusDefault: "— 0",
  },
  states: {
    loading: "加载中",
    loadingReason: "正在读取简历、岗位、模拟面试、资产和薄弱项数据。",
    loadingDetails: "请稍后。",
    errorRecoverHint: "可重试拉取真实业务数据",
    emptyReason: "暂无可展示业务记录。",
    insufficientPrefix: "资料不足",
    placeholderButton: "暂无操作",
    disabledPrefix: "当前状态仅为示意说明",
  },
  sectionOrder: [
    "Section01_AboveTheFold",
    "Section02_TodoSection",
    "Section03_ActivitySection",
  ],
  navigationHint: "导航与 shell 布局沿用当前工作台结构。",
  emptyStates: {
    guidanceTitle: "暂无业务记录",
    guidanceDescription: "创建简历、岗位、模拟面试或资产后会出现在工作台。",
    todoHint: "基于真实业务数据生成。",
    createAction: "进入业务页面",
    guidanceFooter: "",
  },
} as const;

export type DashboardPageCopy = typeof DASHBOARD_PAGE_COPY;
