"""R0 主链路内部 payload 与 response contract。"""

INTERVIEWS_ROUTE_PREFIX = "/interviews"
SESSION_ROUTE = "/{session_id}"
ANSWER_ROUTE = "/{session_id}/answers"

INTERVIEW_FLOW_RECORD_SOURCE = "interview-flow"
DEFAULT_INTERVIEW_MODE = "r0_mock"
SESSION_STATUS_IN_PROGRESS = "in_progress"

FIELD_SESSION_ID = "session_id"
FIELD_RECORD_ID = "record_id"
FIELD_STATUS = "status"
FIELD_MODE = "mode"
FIELD_METADATA = "metadata"
FIELD_PROVIDER_TRACE = "provider_trace"
FIELD_SNAPSHOT_INDEX = "snapshot_index"
FIELD_TRACE_SUMMARY = "trace_summary"
FIELD_TURNS = "turns"
FIELD_TURN_ID = "turn_id"
FIELD_TURN_INDEX = "turn_index"
FIELD_QUESTION = "question"
FIELD_ANSWER = "answer"
FIELD_CONTENT = "content"
FIELD_CURRENT_TURN = "current_turn"
FIELD_NEXT_TURN = "next_turn"
FIELD_PROVIDER = "provider"
FIELD_MODEL = "model"
FIELD_PROVIDER_REQUEST_ID = "provider_request_id"
FIELD_REQUEST_ID = "request_id"
FIELD_FINISH_REASON = "finish_reason"
FIELD_PROMPT_VERSION = "prompt_version"
FIELD_USAGE = "usage"
FIELD_JOB = "job"
FIELD_RESUME = "resume"

ERROR_INTERVIEW_SESSION_NOT_FOUND = "INTERVIEW_SESSION_NOT_FOUND"
ERROR_INTERVIEW_TURN_NOT_FOUND = "INTERVIEW_TURN_NOT_FOUND"
