"""R0 LLM provider contract 使用的集中常量。"""

LLM_PROVIDER_ENV = "LLM_PROVIDER"
LLM_API_KEY_ENV = "LLM_API_KEY"
LLM_MODEL_ENV = "LLM_MODEL"
LLM_TIMEOUT_SECONDS_ENV = "LLM_TIMEOUT_SECONDS"
LLM_BASE_URL_ENV = "LLM_BASE_URL"

LLM_PROVIDER_DETERMINISTIC = "deterministic"
LLM_PROVIDER_OPENAI = "openai"
SUPPORTED_LLM_PROVIDERS = frozenset({LLM_PROVIDER_DETERMINISTIC, LLM_PROVIDER_OPENAI})
TEST_DEV_ENVIRONMENTS = frozenset({"dev", "development", "local", "test", "testing"})

DEFAULT_LLM_TIMEOUT_SECONDS = 30.0
DEFAULT_OPENAI_ENDPOINT = "https://api.openai.com/v1/chat/completions"
DEFAULT_PROMPT_VERSION = "r0-provider-v1"

PURPOSE_QUESTION = "question"
PURPOSE_FOLLOW_UP = "follow_up"
PURPOSE_REVIEW = "review"
PURPOSE_SCORE = "score"
PURPOSE_EXPORT_SUMMARY = "export_summary"

ERROR_LLM_PROVIDER_CONFIG_MISSING = "LLM_PROVIDER_CONFIG_MISSING"
ERROR_LLM_PROVIDER_INVALID = "LLM_PROVIDER_INVALID"
ERROR_LLM_PROVIDER_TIMEOUT = "LLM_PROVIDER_TIMEOUT"
ERROR_LLM_PROVIDER_FAILED = "LLM_PROVIDER_FAILED"
ERROR_LLM_PROVIDER_UNAVAILABLE = "LLM_PROVIDER_UNAVAILABLE"
