"""initial schema"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_checkpoint_refs',
    sa.Column('agent_run_id', sa.String(length=80), nullable=False),
    sa.Column('agent_node_run_id', sa.String(length=80), nullable=True),
    sa.Column('graph_name', sa.String(length=120), nullable=False),
    sa.Column('node_name', sa.String(length=120), nullable=True),
    sa.Column('checkpoint_namespace', sa.String(length=120), nullable=False),
    sa.Column('thread_id', sa.String(length=80), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=120), nullable=False),
    sa.Column('checkpoint_metadata_json', sa.JSON(), nullable=False),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'checkpoint_namespace', 'thread_id', 'checkpoint_id', name='uq_agent_checkpoint_refs_owner_checkpoint')
    )
    op.create_index(op.f('ix_agent_checkpoint_refs_agent_node_run_id'), 'agent_checkpoint_refs', ['agent_node_run_id'], unique=False)
    op.create_index(op.f('ix_agent_checkpoint_refs_agent_run_id'), 'agent_checkpoint_refs', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_checkpoint_refs_owner_id'), 'agent_checkpoint_refs', ['owner_id'], unique=False)
    op.create_index('ix_agent_checkpoint_refs_owner_retention', 'agent_checkpoint_refs', ['owner_id', 'retention_expires_at'], unique=False)
    op.create_index('ix_agent_checkpoint_refs_owner_run', 'agent_checkpoint_refs', ['owner_id', 'agent_run_id'], unique=False)
    op.create_index('ix_agent_checkpoint_refs_owner_thread', 'agent_checkpoint_refs', ['owner_id', 'thread_id'], unique=False)
    op.create_table('agent_interrupts',
    sa.Column('agent_run_id', sa.String(length=80), nullable=False),
    sa.Column('agent_node_run_id', sa.String(length=80), nullable=True),
    sa.Column('node_name', sa.String(length=120), nullable=False),
    sa.Column('interrupt_type', sa.String(length=80), nullable=False),
    sa.Column('resume_schema_id', sa.String(length=120), nullable=False),
    sa.Column('prompt_summary_json', sa.JSON(), nullable=False),
    sa.Column('resume_payload_summary_json', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key_hash', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'id', 'idempotency_key_hash', name='uq_agent_interrupts_owner_idem')
    )
    op.create_index(op.f('ix_agent_interrupts_agent_node_run_id'), 'agent_interrupts', ['agent_node_run_id'], unique=False)
    op.create_index(op.f('ix_agent_interrupts_agent_run_id'), 'agent_interrupts', ['agent_run_id'], unique=False)
    op.create_index('ix_agent_interrupts_owner_expires', 'agent_interrupts', ['owner_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_agent_interrupts_owner_id'), 'agent_interrupts', ['owner_id'], unique=False)
    op.create_index('ix_agent_interrupts_owner_node', 'agent_interrupts', ['owner_id', 'node_name'], unique=False)
    op.create_index('ix_agent_interrupts_owner_run', 'agent_interrupts', ['owner_id', 'agent_run_id'], unique=False)
    op.create_table('agent_node_runs',
    sa.Column('agent_run_id', sa.String(length=80), nullable=False),
    sa.Column('graph_name', sa.String(length=120), nullable=False),
    sa.Column('node_name', sa.String(length=120), nullable=False),
    sa.Column('node_version', sa.String(length=80), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('llm_call_ids_json', sa.JSON(), nullable=False),
    sa.Column('side_effect_keys_json', sa.JSON(), nullable=False),
    sa.Column('input_digest', sa.String(length=128), nullable=True),
    sa.Column('output_digest', sa.String(length=128), nullable=True),
    sa.Column('validation_summary_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'agent_run_id', 'node_name', 'attempt_number', name='uq_agent_node_runs_attempt')
    )
    op.create_index(op.f('ix_agent_node_runs_agent_run_id'), 'agent_node_runs', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_node_runs_owner_id'), 'agent_node_runs', ['owner_id'], unique=False)
    op.create_index('ix_agent_node_runs_owner_node', 'agent_node_runs', ['owner_id', 'node_name'], unique=False)
    op.create_index('ix_agent_node_runs_owner_run', 'agent_node_runs', ['owner_id', 'agent_run_id'], unique=False)
    op.create_index('ix_agent_node_runs_owner_status', 'agent_node_runs', ['owner_id', 'status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('ai_task_id', sa.String(length=80), nullable=True),
    sa.Column('graph_name', sa.String(length=120), nullable=False),
    sa.Column('graph_version', sa.String(length=80), nullable=False),
    sa.Column('entrypoint_name', sa.String(length=120), nullable=False),
    sa.Column('thread_id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key_hash', sa.String(length=128), nullable=True),
    sa.Column('input_refs_json', sa.JSON(), nullable=False),
    sa.Column('output_refs_json', sa.JSON(), nullable=False),
    sa.Column('pending_writes_json', sa.JSON(), nullable=False),
    sa.Column('error_summary_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interrupted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'graph_name', 'idempotency_key_hash', name='uq_agent_runs_owner_graph_idem'),
    sa.UniqueConstraint('owner_id', 'thread_id', name='uq_agent_runs_owner_thread')
    )
    op.create_index('ix_agent_runs_owner_graph', 'agent_runs', ['owner_id', 'graph_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_owner_id'), 'agent_runs', ['owner_id'], unique=False)
    op.create_index('ix_agent_runs_owner_status', 'agent_runs', ['owner_id', 'status'], unique=False)
    op.create_index('ix_agent_runs_owner_task', 'agent_runs', ['owner_id', 'ai_task_id'], unique=False)
    op.create_index('ix_agent_runs_owner_thread', 'agent_runs', ['owner_id', 'thread_id'], unique=False)
    op.create_table('ai_task_results',
    sa.Column('ai_task_id', sa.String(length=80), nullable=False),
    sa.Column('result_sequence', sa.String(length=40), nullable=False),
    sa.Column('validation_result_ref_id', sa.String(length=80), nullable=True),
    sa.Column('trace_ref_id', sa.String(length=80), nullable=True),
    sa.Column('result_ref_id', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_task_results_ai_task_id'), 'ai_task_results', ['ai_task_id'], unique=False)
    op.create_index(op.f('ix_ai_task_results_owner_id'), 'ai_task_results', ['owner_id'], unique=False)
    op.create_table('ai_tasks',
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('contract_ids', sa.JSON(), nullable=True),
    sa.Column('idempotency_record_id', sa.String(length=80), nullable=True),
    sa.Column('target_ref_id', sa.String(length=80), nullable=True),
    sa.Column('timeout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tasks_owner_id'), 'ai_tasks', ['owner_id'], unique=False)
    op.create_table('answers',
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('question_id', sa.String(length=80), nullable=False),
    sa.Column('answer_round', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_owner_id'), 'answers', ['owner_id'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_answers_session_id'), 'answers', ['session_id'], unique=False)
    op.create_table('api_request_traces',
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('trace_id', sa.String(length=80), nullable=False),
    sa.Column('audit_event_id', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_request_traces_owner_id'), 'api_request_traces', ['owner_id'], unique=False)
    op.create_index(op.f('ix_api_request_traces_request_id'), 'api_request_traces', ['request_id'], unique=False)
    op.create_index(op.f('ix_api_request_traces_trace_id'), 'api_request_traces', ['trace_id'], unique=False)
    op.create_table('asset_versions',
    sa.Column('asset_id', sa.String(length=80), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('edit_summary', sa.Text(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=80), nullable=True),
    sa.Column('created_from_candidate_id', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_versions_asset_id'), 'asset_versions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_versions_owner_id'), 'asset_versions', ['owner_id'], unique=False)
    op.create_table('assets',
    sa.Column('normalized_title', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.String(length=80), nullable=True),
    sa.Column('source_refs_json', sa.JSON(), nullable=True),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=True),
    sa.Column('trace_refs_json', sa.JSON(), nullable=True),
    sa.Column('resume_version_ref_json', sa.JSON(), nullable=True),
    sa.Column('job_version_ref_json', sa.JSON(), nullable=True),
    sa.Column('question_pattern', sa.String(length=120), nullable=True),
    sa.Column('created_from_candidate_id', sa.String(length=80), nullable=True),
    sa.Column('user_confirmation_ref_json', sa.JSON(), nullable=True),
    sa.Column('fact_source', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('api_request_trace_id', sa.String(length=80), nullable=True),
    sa.Column('target_ref_id', sa.String(length=80), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_owner_id'), 'audit_events', ['owner_id'], unique=False)
    op.create_table('evidence_refs',
    sa.Column('source_ref_id', sa.String(length=80), nullable=False),
    sa.Column('version_ref_id', sa.String(length=80), nullable=True),
    sa.Column('snapshot_ref_id', sa.String(length=80), nullable=True),
    sa.Column('evidence_hash', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_refs_owner_id'), 'evidence_refs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_evidence_refs_source_ref_id'), 'evidence_refs', ['source_ref_id'], unique=False)
    op.create_table('feedback',
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('answer_id', sa.String(length=80), nullable=False),
    sa.Column('ai_task_id', sa.String(length=80), nullable=True),
    sa.Column('score_result_id', sa.String(length=80), nullable=True),
    sa.Column('feedback_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_answer_id'), 'feedback', ['answer_id'], unique=False)
    op.create_index(op.f('ix_feedback_owner_id'), 'feedback', ['owner_id'], unique=False)
    op.create_index(op.f('ix_feedback_session_id'), 'feedback', ['session_id'], unique=False)
    op.create_table('interview_reports',
    sa.Column('session_id', sa.String(length=80), nullable=True),
    sa.Column('ai_task_id', sa.String(length=80), nullable=True),
    sa.Column('score_result_id', sa.String(length=80), nullable=True),
    sa.Column('report_type', sa.String(length=80), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_reports_owner_id'), 'interview_reports', ['owner_id'], unique=False)
    op.create_table('interview_reviews',
    sa.Column('session_id', sa.String(length=80), nullable=True),
    sa.Column('report_id', sa.String(length=80), nullable=True),
    sa.Column('real_interview_input_ref_id', sa.String(length=80), nullable=True),
    sa.Column('ai_task_id', sa.String(length=80), nullable=True),
    sa.Column('review_type', sa.String(length=80), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_reviews_owner_id'), 'interview_reviews', ['owner_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('binding_id', sa.String(length=80), nullable=True),
    sa.Column('resume_id', sa.String(length=80), nullable=True),
    sa.Column('resume_version_id', sa.String(length=80), nullable=True),
    sa.Column('job_id', sa.String(length=80), nullable=True),
    sa.Column('job_version_id', sa.String(length=80), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_owner_id'), 'interview_sessions', ['owner_id'], unique=False)
    op.create_table('job_match_analyses',
    sa.Column('binding_id', sa.String(length=80), nullable=False),
    sa.Column('resume_id', sa.String(length=80), nullable=False),
    sa.Column('resume_version_id', sa.String(length=80), nullable=False),
    sa.Column('job_id', sa.String(length=80), nullable=False),
    sa.Column('job_version_id', sa.String(length=80), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('overall_level', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('result_payload_json', sa.JSON(), nullable=False),
    sa.Column('markdown_report_text', sa.Text(), nullable=True),
    sa.Column('score_rule_version', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('source_digest', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_match_analyses_binding_id'), 'job_match_analyses', ['binding_id'], unique=False)
    op.create_index(op.f('ix_job_match_analyses_job_id'), 'job_match_analyses', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_match_analyses_owner_id'), 'job_match_analyses', ['owner_id'], unique=False)
    op.create_index(op.f('ix_job_match_analyses_resume_id'), 'job_match_analyses', ['resume_id'], unique=False)
    op.create_table('job_versions',
    sa.Column('job_id', sa.String(length=80), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('other_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_versions_job_id'), 'job_versions', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_versions_owner_id'), 'job_versions', ['owner_id'], unique=False)
    op.create_table('jobs',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('department', sa.String(length=160), nullable=True),
    sa.Column('application_status', sa.String(length=64), nullable=False),
    sa.Column('current_version_id', sa.String(length=80), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_current_version_id'), 'jobs', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_jobs_owner_id'), 'jobs', ['owner_id'], unique=False)
    op.create_table('llm_call_payloads',
    sa.Column('llm_call_id', sa.String(length=80), nullable=False),
    sa.Column('payload_kind', sa.String(length=80), nullable=False),
    sa.Column('capture_policy_version', sa.String(length=80), nullable=False),
    sa.Column('sanitized', sa.Boolean(), nullable=False),
    sa.Column('raw_enabled', sa.Boolean(), nullable=False),
    sa.Column('payload_summary_json', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=128), nullable=True),
    sa.Column('raw_payload_ciphertext_ref', sa.String(length=240), nullable=True),
    sa.Column('encryption_key_ref', sa.String(length=240), nullable=True),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_audit_ref_id', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'llm_call_id', 'payload_kind', name='uq_llm_call_payloads_owner_call_kind')
    )
    op.create_index(op.f('ix_llm_call_payloads_llm_call_id'), 'llm_call_payloads', ['llm_call_id'], unique=False)
    op.create_index('ix_llm_call_payloads_owner_call', 'llm_call_payloads', ['owner_id', 'llm_call_id'], unique=False)
    op.create_index(op.f('ix_llm_call_payloads_owner_id'), 'llm_call_payloads', ['owner_id'], unique=False)
    op.create_index('ix_llm_call_payloads_owner_kind', 'llm_call_payloads', ['owner_id', 'payload_kind'], unique=False)
    op.create_index('ix_llm_call_payloads_owner_raw', 'llm_call_payloads', ['owner_id', 'raw_enabled'], unique=False)
    op.create_index('ix_llm_call_payloads_owner_retention', 'llm_call_payloads', ['owner_id', 'retention_expires_at'], unique=False)
    op.create_table('llm_calls',
    sa.Column('ai_task_id', sa.String(length=80), nullable=True),
    sa.Column('agent_run_id', sa.String(length=80), nullable=True),
    sa.Column('agent_node_run_id', sa.String(length=80), nullable=True),
    sa.Column('graph_name', sa.String(length=120), nullable=True),
    sa.Column('node_name', sa.String(length=120), nullable=True),
    sa.Column('contract_ids_json', sa.JSON(), nullable=False),
    sa.Column('configured_model', sa.String(length=120), nullable=True),
    sa.Column('provider_model', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=120), nullable=True),
    sa.Column('schema_id', sa.String(length=120), nullable=True),
    sa.Column('request_hash', sa.String(length=128), nullable=True),
    sa.Column('response_hash', sa.String(length=128), nullable=True),
    sa.Column('evidence_hash', sa.String(length=128), nullable=True),
    sa.Column('usage_json', sa.JSON(), nullable=True),
    sa.Column('fallback_reason', sa.String(length=240), nullable=True),
    sa.Column('validation_errors_json', sa.JSON(), nullable=True),
    sa.Column('low_confidence_flags_json', sa.JSON(), nullable=True),
    sa.Column('error_summary_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_agent_node_run_id'), 'llm_calls', ['agent_node_run_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_agent_run_id'), 'llm_calls', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_owner_id'), 'llm_calls', ['owner_id'], unique=False)
    op.create_index('ix_llm_calls_owner_model', 'llm_calls', ['owner_id', 'configured_model'], unique=False)
    op.create_index('ix_llm_calls_owner_run', 'llm_calls', ['owner_id', 'agent_run_id'], unique=False)
    op.create_index('ix_llm_calls_owner_status', 'llm_calls', ['owner_id', 'status'], unique=False)
    op.create_index('ix_llm_calls_owner_task', 'llm_calls', ['owner_id', 'ai_task_id'], unique=False)
    op.create_table('low_confidence_flags',
    sa.Column('target_ref_id', sa.String(length=80), nullable=False),
    sa.Column('validation_result_ref_id', sa.String(length=80), nullable=True),
    sa.Column('trace_ref_id', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('impact_scope', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_low_confidence_flags_owner_id'), 'low_confidence_flags', ['owner_id'], unique=False)
    op.create_index(op.f('ix_low_confidence_flags_target_ref_id'), 'low_confidence_flags', ['target_ref_id'], unique=False)
    op.create_table('polish_candidates',
    sa.Column('candidate_id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('candidate_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_refs_json', sa.JSON(), nullable=False),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('trace_refs_json', sa.JSON(), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('question_id', sa.String(length=80), nullable=False),
    sa.Column('answer_id', sa.String(length=80), nullable=False),
    sa.Column('feedback_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence_excerpt', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence_level', sa.String(length=40), nullable=False),
    sa.Column('merge_key', sa.String(length=520), nullable=False),
    sa.Column('merge_target_candidate_id', sa.String(length=80), nullable=True),
    sa.Column('target_formal_ref_json', sa.JSON(), nullable=True),
    sa.Column('candidate_payload_json', sa.JSON(), nullable=False),
    sa.Column('user_confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id', 'owner_id'),
    sa.UniqueConstraint('owner_id', 'merge_key', name='uq_polish_candidates_owner_merge_key')
    )
    op.create_index(op.f('ix_polish_candidates_answer_id'), 'polish_candidates', ['answer_id'], unique=False)
    op.create_index(op.f('ix_polish_candidates_candidate_type'), 'polish_candidates', ['candidate_type'], unique=False)
    op.create_index(op.f('ix_polish_candidates_confidence_level'), 'polish_candidates', ['confidence_level'], unique=False)
    op.create_index(op.f('ix_polish_candidates_feedback_id'), 'polish_candidates', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_polish_candidates_question_id'), 'polish_candidates', ['question_id'], unique=False)
    op.create_index(op.f('ix_polish_candidates_session_id'), 'polish_candidates', ['session_id'], unique=False)
    op.create_index(op.f('ix_polish_candidates_source_type'), 'polish_candidates', ['source_type'], unique=False)
    op.create_index(op.f('ix_polish_candidates_status'), 'polish_candidates', ['status'], unique=False)
    op.create_table('polish_session_details',
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('topic_ref_id', sa.String(length=80), nullable=True),
    sa.Column('subtopic_ref_id', sa.String(length=80), nullable=True),
    sa.Column('custom_topic_text_summary', sa.String(length=240), nullable=True),
    sa.Column('progress_tree_status', sa.String(length=40), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('progress_tree_plan_json', sa.JSON(), nullable=True),
    sa.Column('progress_tree_state_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_polish_session_details_owner_id'), 'polish_session_details', ['owner_id'], unique=False)
    op.create_table('pressure_session_details',
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_pressure_session_details_owner_id'), 'pressure_session_details', ['owner_id'], unique=False)
    op.create_table('questions',
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('ai_task_id', sa.String(length=80), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('question_sources_json', sa.JSON(), nullable=True),
    sa.Column('question_metadata_json', sa.JSON(), nullable=True),
    sa.Column('progress_node_ref', sa.String(length=120), nullable=True),
    sa.Column('context_digest', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_owner_id'), 'questions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_questions_session_id'), 'questions', ['session_id'], unique=False)
    op.create_table('report_sections',
    sa.Column('report_id', sa.String(length=80), nullable=False),
    sa.Column('section_key', sa.String(length=80), nullable=False),
    sa.Column('score_result_id', sa.String(length=80), nullable=True),
    sa.Column('section_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_sections_owner_id'), 'report_sections', ['owner_id'], unique=False)
    op.create_index(op.f('ix_report_sections_report_id'), 'report_sections', ['report_id'], unique=False)
    op.create_table('resume_job_bindings',
    sa.Column('resume_id', sa.String(length=80), nullable=False),
    sa.Column('job_id', sa.String(length=80), nullable=False),
    sa.Column('resume_version_id', sa.String(length=80), nullable=False),
    sa.Column('job_version_id', sa.String(length=80), nullable=False),
    sa.Column('unbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unbound_by', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_job_bindings_job_id'), 'resume_job_bindings', ['job_id'], unique=False)
    op.create_index(op.f('ix_resume_job_bindings_owner_id'), 'resume_job_bindings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_resume_job_bindings_resume_id'), 'resume_job_bindings', ['resume_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('resume_id', sa.String(length=80), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('markdown_text', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_owner_id'), 'resume_versions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.create_table('resumes',
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('current_version_id', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_owner_id'), 'resumes', ['owner_id'], unique=False)
    op.create_table('score_dimensions',
    sa.Column('score_rule_version_id', sa.String(length=80), nullable=False),
    sa.Column('dimension_key', sa.String(length=80), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_dimensions_owner_id'), 'score_dimensions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_score_dimensions_score_rule_version_id'), 'score_dimensions', ['score_rule_version_id'], unique=False)
    op.create_table('score_evidence_links',
    sa.Column('score_result_id', sa.String(length=80), nullable=False),
    sa.Column('score_dimension_id', sa.String(length=80), nullable=True),
    sa.Column('evidence_ref_id', sa.String(length=80), nullable=False),
    sa.Column('evidence_role', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_evidence_links_evidence_ref_id'), 'score_evidence_links', ['evidence_ref_id'], unique=False)
    op.create_index(op.f('ix_score_evidence_links_owner_id'), 'score_evidence_links', ['owner_id'], unique=False)
    op.create_index(op.f('ix_score_evidence_links_score_result_id'), 'score_evidence_links', ['score_result_id'], unique=False)
    op.create_table('score_results',
    sa.Column('score_type', sa.String(length=64), nullable=False),
    sa.Column('target_ref_id', sa.String(length=80), nullable=False),
    sa.Column('score_rule_version_id', sa.String(length=80), nullable=True),
    sa.Column('ai_task_id', sa.String(length=80), nullable=True),
    sa.Column('score_value', sa.Integer(), nullable=True),
    sa.Column('score_version', sa.String(length=64), nullable=True),
    sa.Column('rubric_version', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_results_owner_id'), 'score_results', ['owner_id'], unique=False)
    op.create_index(op.f('ix_score_results_target_ref_id'), 'score_results', ['target_ref_id'], unique=False)
    op.create_table('score_rule_sets',
    sa.Column('score_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_rule_sets_owner_id'), 'score_rule_sets', ['owner_id'], unique=False)
    op.create_table('score_rule_versions',
    sa.Column('score_rule_set_id', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_rule_versions_owner_id'), 'score_rule_versions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_score_rule_versions_score_rule_set_id'), 'score_rule_versions', ['score_rule_set_id'], unique=False)
    op.create_table('trace_refs',
    sa.Column('api_request_trace_id', sa.String(length=80), nullable=True),
    sa.Column('ai_task_id', sa.String(length=80), nullable=True),
    sa.Column('audit_event_id', sa.String(length=80), nullable=True),
    sa.Column('trace_kind', sa.String(length=80), nullable=False),
    sa.Column('trace_key', sa.String(length=160), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_refs_owner_id'), 'trace_refs', ['owner_id'], unique=False)
    op.create_table('training_recommendations',
    sa.Column('normalized_topic', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.String(length=40), nullable=True),
    sa.Column('source_refs_json', sa.JSON(), nullable=True),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=True),
    sa.Column('trace_refs_json', sa.JSON(), nullable=True),
    sa.Column('candidate_ref_json', sa.JSON(), nullable=True),
    sa.Column('target_weakness_refs_json', sa.JSON(), nullable=True),
    sa.Column('question_pattern', sa.String(length=120), nullable=True),
    sa.Column('expected_answer_dimensions_json', sa.JSON(), nullable=True),
    sa.Column('created_from_candidate_id', sa.String(length=80), nullable=True),
    sa.Column('user_confirmation_ref_json', sa.JSON(), nullable=True),
    sa.Column('ai_task_id', sa.String(length=80), nullable=True),
    sa.Column('confirmation_id', sa.String(length=80), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_recommendations_owner_id'), 'training_recommendations', ['owner_id'], unique=False)
    op.create_table('training_tasks',
    sa.Column('training_recommendation_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('target_weakness_refs_json', sa.JSON(), nullable=True),
    sa.Column('question_pattern', sa.String(length=120), nullable=True),
    sa.Column('expected_answer_dimensions_json', sa.JSON(), nullable=True),
    sa.Column('source_refs_json', sa.JSON(), nullable=True),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=True),
    sa.Column('trace_refs_json', sa.JSON(), nullable=True),
    sa.Column('explicit_action_ref_json', sa.JSON(), nullable=True),
    sa.Column('progress_update_hint_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_tasks_owner_id'), 'training_tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_training_tasks_training_recommendation_id'), 'training_tasks', ['training_recommendation_id'], unique=False)
    op.create_table('user_accounts',
    sa.Column('email_normalized', sa.String(length=320), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_normalized')
    )
    op.create_index(op.f('ix_user_accounts_owner_id'), 'user_accounts', ['owner_id'], unique=False)
    op.create_table('user_confirmations',
    sa.Column('target_ref_id', sa.String(length=80), nullable=False),
    sa.Column('audit_event_id', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('before_summary', sa.Text(), nullable=True),
    sa.Column('after_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_confirmations_owner_id'), 'user_confirmations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_user_confirmations_target_ref_id'), 'user_confirmations', ['target_ref_id'], unique=False)
    op.create_table('weakness_candidates',
    sa.Column('normalized_title', sa.String(length=200), nullable=False),
    sa.Column('ai_task_id', sa.String(length=80), nullable=True),
    sa.Column('target_weakness_id', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weakness_candidates_owner_id'), 'weakness_candidates', ['owner_id'], unique=False)
    op.create_table('weaknesses',
    sa.Column('normalized_title', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('severity_hint', sa.String(length=40), nullable=True),
    sa.Column('confidence_level', sa.String(length=40), nullable=True),
    sa.Column('source_refs_json', sa.JSON(), nullable=True),
    sa.Column('session_refs_json', sa.JSON(), nullable=True),
    sa.Column('feedback_refs_json', sa.JSON(), nullable=True),
    sa.Column('question_refs_json', sa.JSON(), nullable=True),
    sa.Column('answer_refs_json', sa.JSON(), nullable=True),
    sa.Column('loss_point_refs_json', sa.JSON(), nullable=True),
    sa.Column('repeated_loss_point_refs_json', sa.JSON(), nullable=True),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=True),
    sa.Column('trace_refs_json', sa.JSON(), nullable=True),
    sa.Column('created_from_candidate_id', sa.String(length=80), nullable=True),
    sa.Column('user_confirmation_ref_json', sa.JSON(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_ref_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaknesses_owner_id'), 'weaknesses', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weaknesses_owner_id'), table_name='weaknesses')
    op.drop_table('weaknesses')
    op.drop_index(op.f('ix_weakness_candidates_owner_id'), table_name='weakness_candidates')
    op.drop_table('weakness_candidates')
    op.drop_index(op.f('ix_user_confirmations_target_ref_id'), table_name='user_confirmations')
    op.drop_index(op.f('ix_user_confirmations_owner_id'), table_name='user_confirmations')
    op.drop_table('user_confirmations')
    op.drop_index(op.f('ix_user_accounts_owner_id'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_index(op.f('ix_training_tasks_training_recommendation_id'), table_name='training_tasks')
    op.drop_index(op.f('ix_training_tasks_owner_id'), table_name='training_tasks')
    op.drop_table('training_tasks')
    op.drop_index(op.f('ix_training_recommendations_owner_id'), table_name='training_recommendations')
    op.drop_table('training_recommendations')
    op.drop_index(op.f('ix_trace_refs_owner_id'), table_name='trace_refs')
    op.drop_table('trace_refs')
    op.drop_index(op.f('ix_score_rule_versions_score_rule_set_id'), table_name='score_rule_versions')
    op.drop_index(op.f('ix_score_rule_versions_owner_id'), table_name='score_rule_versions')
    op.drop_table('score_rule_versions')
    op.drop_index(op.f('ix_score_rule_sets_owner_id'), table_name='score_rule_sets')
    op.drop_table('score_rule_sets')
    op.drop_index(op.f('ix_score_results_target_ref_id'), table_name='score_results')
    op.drop_index(op.f('ix_score_results_owner_id'), table_name='score_results')
    op.drop_table('score_results')
    op.drop_index(op.f('ix_score_evidence_links_score_result_id'), table_name='score_evidence_links')
    op.drop_index(op.f('ix_score_evidence_links_owner_id'), table_name='score_evidence_links')
    op.drop_index(op.f('ix_score_evidence_links_evidence_ref_id'), table_name='score_evidence_links')
    op.drop_table('score_evidence_links')
    op.drop_index(op.f('ix_score_dimensions_score_rule_version_id'), table_name='score_dimensions')
    op.drop_index(op.f('ix_score_dimensions_owner_id'), table_name='score_dimensions')
    op.drop_table('score_dimensions')
    op.drop_index(op.f('ix_resumes_owner_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_owner_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_resume_job_bindings_resume_id'), table_name='resume_job_bindings')
    op.drop_index(op.f('ix_resume_job_bindings_owner_id'), table_name='resume_job_bindings')
    op.drop_index(op.f('ix_resume_job_bindings_job_id'), table_name='resume_job_bindings')
    op.drop_table('resume_job_bindings')
    op.drop_index(op.f('ix_report_sections_report_id'), table_name='report_sections')
    op.drop_index(op.f('ix_report_sections_owner_id'), table_name='report_sections')
    op.drop_table('report_sections')
    op.drop_index(op.f('ix_questions_session_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_owner_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_pressure_session_details_owner_id'), table_name='pressure_session_details')
    op.drop_table('pressure_session_details')
    op.drop_index(op.f('ix_polish_session_details_owner_id'), table_name='polish_session_details')
    op.drop_table('polish_session_details')
    op.drop_index(op.f('ix_polish_candidates_status'), table_name='polish_candidates')
    op.drop_index(op.f('ix_polish_candidates_source_type'), table_name='polish_candidates')
    op.drop_index(op.f('ix_polish_candidates_session_id'), table_name='polish_candidates')
    op.drop_index(op.f('ix_polish_candidates_question_id'), table_name='polish_candidates')
    op.drop_index(op.f('ix_polish_candidates_feedback_id'), table_name='polish_candidates')
    op.drop_index(op.f('ix_polish_candidates_confidence_level'), table_name='polish_candidates')
    op.drop_index(op.f('ix_polish_candidates_candidate_type'), table_name='polish_candidates')
    op.drop_index(op.f('ix_polish_candidates_answer_id'), table_name='polish_candidates')
    op.drop_table('polish_candidates')
    op.drop_index(op.f('ix_low_confidence_flags_target_ref_id'), table_name='low_confidence_flags')
    op.drop_index(op.f('ix_low_confidence_flags_owner_id'), table_name='low_confidence_flags')
    op.drop_table('low_confidence_flags')
    op.drop_index('ix_llm_calls_owner_task', table_name='llm_calls')
    op.drop_index('ix_llm_calls_owner_status', table_name='llm_calls')
    op.drop_index('ix_llm_calls_owner_run', table_name='llm_calls')
    op.drop_index('ix_llm_calls_owner_model', table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_owner_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_agent_run_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_agent_node_run_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('ix_llm_call_payloads_owner_retention', table_name='llm_call_payloads')
    op.drop_index('ix_llm_call_payloads_owner_raw', table_name='llm_call_payloads')
    op.drop_index('ix_llm_call_payloads_owner_kind', table_name='llm_call_payloads')
    op.drop_index(op.f('ix_llm_call_payloads_owner_id'), table_name='llm_call_payloads')
    op.drop_index('ix_llm_call_payloads_owner_call', table_name='llm_call_payloads')
    op.drop_index(op.f('ix_llm_call_payloads_llm_call_id'), table_name='llm_call_payloads')
    op.drop_table('llm_call_payloads')
    op.drop_index(op.f('ix_jobs_owner_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_current_version_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_versions_owner_id'), table_name='job_versions')
    op.drop_index(op.f('ix_job_versions_job_id'), table_name='job_versions')
    op.drop_table('job_versions')
    op.drop_index(op.f('ix_job_match_analyses_resume_id'), table_name='job_match_analyses')
    op.drop_index(op.f('ix_job_match_analyses_owner_id'), table_name='job_match_analyses')
    op.drop_index(op.f('ix_job_match_analyses_job_id'), table_name='job_match_analyses')
    op.drop_index(op.f('ix_job_match_analyses_binding_id'), table_name='job_match_analyses')
    op.drop_table('job_match_analyses')
    op.drop_index(op.f('ix_interview_sessions_owner_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_interview_reviews_owner_id'), table_name='interview_reviews')
    op.drop_table('interview_reviews')
    op.drop_index(op.f('ix_interview_reports_owner_id'), table_name='interview_reports')
    op.drop_table('interview_reports')
    op.drop_index(op.f('ix_feedback_session_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_owner_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_answer_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_evidence_refs_source_ref_id'), table_name='evidence_refs')
    op.drop_index(op.f('ix_evidence_refs_owner_id'), table_name='evidence_refs')
    op.drop_table('evidence_refs')
    op.drop_index(op.f('ix_audit_events_owner_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_asset_versions_owner_id'), table_name='asset_versions')
    op.drop_index(op.f('ix_asset_versions_asset_id'), table_name='asset_versions')
    op.drop_table('asset_versions')
    op.drop_index(op.f('ix_api_request_traces_trace_id'), table_name='api_request_traces')
    op.drop_index(op.f('ix_api_request_traces_request_id'), table_name='api_request_traces')
    op.drop_index(op.f('ix_api_request_traces_owner_id'), table_name='api_request_traces')
    op.drop_table('api_request_traces')
    op.drop_index(op.f('ix_answers_session_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_owner_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_ai_tasks_owner_id'), table_name='ai_tasks')
    op.drop_table('ai_tasks')
    op.drop_index(op.f('ix_ai_task_results_owner_id'), table_name='ai_task_results')
    op.drop_index(op.f('ix_ai_task_results_ai_task_id'), table_name='ai_task_results')
    op.drop_table('ai_task_results')
    op.drop_index('ix_agent_runs_owner_thread', table_name='agent_runs')
    op.drop_index('ix_agent_runs_owner_task', table_name='agent_runs')
    op.drop_index('ix_agent_runs_owner_status', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_owner_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_owner_graph', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_agent_node_runs_owner_status', table_name='agent_node_runs')
    op.drop_index('ix_agent_node_runs_owner_run', table_name='agent_node_runs')
    op.drop_index('ix_agent_node_runs_owner_node', table_name='agent_node_runs')
    op.drop_index(op.f('ix_agent_node_runs_owner_id'), table_name='agent_node_runs')
    op.drop_index(op.f('ix_agent_node_runs_agent_run_id'), table_name='agent_node_runs')
    op.drop_table('agent_node_runs')
    op.drop_index('ix_agent_interrupts_owner_run', table_name='agent_interrupts')
    op.drop_index('ix_agent_interrupts_owner_node', table_name='agent_interrupts')
    op.drop_index(op.f('ix_agent_interrupts_owner_id'), table_name='agent_interrupts')
    op.drop_index('ix_agent_interrupts_owner_expires', table_name='agent_interrupts')
    op.drop_index(op.f('ix_agent_interrupts_agent_run_id'), table_name='agent_interrupts')
    op.drop_index(op.f('ix_agent_interrupts_agent_node_run_id'), table_name='agent_interrupts')
    op.drop_table('agent_interrupts')
    op.drop_index('ix_agent_checkpoint_refs_owner_thread', table_name='agent_checkpoint_refs')
    op.drop_index('ix_agent_checkpoint_refs_owner_run', table_name='agent_checkpoint_refs')
    op.drop_index('ix_agent_checkpoint_refs_owner_retention', table_name='agent_checkpoint_refs')
    op.drop_index(op.f('ix_agent_checkpoint_refs_owner_id'), table_name='agent_checkpoint_refs')
    op.drop_index(op.f('ix_agent_checkpoint_refs_agent_run_id'), table_name='agent_checkpoint_refs')
    op.drop_index(op.f('ix_agent_checkpoint_refs_agent_node_run_id'), table_name='agent_checkpoint_refs')
    op.drop_table('agent_checkpoint_refs')
    # ### end Alembic commands ###
